### ISSUE TITLE
Support direct commit to main

### ISSUE THREAD

**Issue by kpx-dev** [severity1/gazoo#28]
When testing my repo, I commit directly to main. This action failed. Looks like it only designed for PR. Would be nice to support direct commit as well for easier testing.

**Comment by severity1** [comment]
Hi @kpx-dev I just got back form a long holiday, yes ATM this is only designed for PR as it makes comment on the PR itself. Can you give me usecases that would need direct commit support? To be able to support  for direct commit one thing that needs to be done first is to add support for inline comments.

**Comment by kpx-dev** [comment]
@severity1 hi John, it’s more for onboarding support. When I first integrate with this action, I needed to setup proper access to aws account so having it support 1 successful invoke would be nice.

**Comment by severity1** [comment]
@kpx-dev i just realised that we dont need to make inline comments work for this as long as a commit can trigger this i can make it work so that the important parts run and if its not being triggered through a PR event then skip the part where it coents on the PR. 

I'll submit a PR with this.

**Comment by severity1** [comment]
@kpx-dev please try v0.10.0 against push events.

**Comment by kpx-dev** [comment]
@severity1 Thank you, all work great now! I guess small warning is to upgrade Node: 


The following actions use a deprecated Node.js version and will be forced to run on node20: severity1/custom-amazon-bedrock-agent-action@v0.10.0. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by severity1** [comment]
yeah ive got  dependabot PRs in queue jus tjeed to test them before i merge.
